apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-sock-shop
  namespace: argocd
spec:
  destination:
    namespace: sock-shop
    server: https://kubernetes.default.svc
  project: sock-shop
  source:
    helm:
      valueFiles:
        - values.yaml
    path: deploy/kubernetes/helm-chart
    repoURL: https://github.com/canerturkaslan/microservices-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true